name: Process one target


on:
  workflow_call:
    inputs:

      texlive_digest:
        required: true
        type: string

      timestamp:
        required: true
        type: string

      target:
        required: true
        type: string

      flags:
        required: true
        type: string

      pre_tex:
        required: true
        type: string

      flavours:
        required: true
        type: string

      publish:
        required: true
        type: boolean


jobs:

  record:
    name: Record compilation information for ${{ inputs.target }}
    if: inputs.publish == true

    runs-on: ubuntu-latest

    steps:
      - name: Write compilation information for ${{ inputs.target }}
        run: |
          ENV_FILE="compilation_info-${{ inputs.target }}.txt"
          echo "" >> $ENV_FILE
          echo "jobname: ${{ inputs.target }}" >> $ENV_FILE
          #echo "flags: ${{ inputs.flags }}" >> $ENV_FILE
          echo "pre-tex: ${{ inputs.pre_tex }}" >> $ENV_FILE
          echo "PDF standards: ${{ inputs.flavours }}" >> $ENV_FILE

      - name: Upload compilation information file for ${{ inputs.target }}
        uses: actions/upload-artifact@v7
        with:
          name: compilation-info-${{ inputs.target }}
          path: compilation_info-${{ inputs.target }}.txt


  build:
    name: Build ${{ inputs.target }}

    uses: ./.github/workflows/build.yml
    with:
      texlive_digest: ${{ inputs.texlive_digest }}
      timestamp: ${{ inputs.timestamp }}
      filename: ${{ inputs.target }}
      flags: ${{ inputs.flags }}
      pre_tex: ${{ inputs.pre_tex }}
      label: first
      publish: ${{ inputs.publish }}


  validate:
    name: Validate ${{ inputs.target }}
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Download ${{ inputs.target }} PDF from build job
        uses: actions/download-artifact@v7
        with:
          name: pdf-first-build-publish-${{ inputs.publish }}-${{ inputs.target }}
          path: .

      - name: Validate ${{ inputs.target }} against PDF standards ${{ inputs.flavours }}
        run: |
          for flav in ${{ inputs.flavours }}; do
            output=$(docker run --rm -v "$(pwd)":/data verapdf/cli --flavour $flav --format text "./${{ inputs.target }}.pdf")
            if [[ "$output" != PASS* ]]; then
              exit 1
            fi
          done


  reproduce:
    name: Build ${{ inputs.target }} again
    needs: build

    uses: ./.github/workflows/build.yml
    with:
      texlive_digest: ${{ inputs.texlive_digest }}
      timestamp: ${{ inputs.timestamp }}
      filename: ${{ inputs.target }}
      flags: ${{ inputs.flags }}
      pre_tex: ${{ inputs.pre_tex }}
      label: second
      publish: ${{ inputs.publish }}


  compare:
    name: Check build reproducibility
    needs: reproduce

    runs-on: ubuntu-latest

    steps:
      - name: Create directories to download built PDFs
        run: sudo mkdir first second

      - name: Download first PDF build of ${{ inputs.target }}
        uses: actions/download-artifact@v7
        with:
          name: pdf-first-build-publish-${{ inputs.publish }}-${{ inputs.target }}
          path: .

      - name: Move first PDF build of ${{ inputs.target }} to its directory
        run: sudo mv ${{ inputs.target }}.pdf first/${{ inputs.target }}.pdf

      - name: Download second PDF build of ${{ inputs.target }}
        uses: actions/download-artifact@v7
        with:
          name: pdf-second-build-publish-${{ inputs.publish }}-${{ inputs.target }}
          path: .

      - name: Move second PDF build of ${{ inputs.target }} to its directory
        run: sudo mv ${{ inputs.target }}.pdf second/${{ inputs.target }}.pdf

      - name: Check if the two builds of ${{ inputs.target }} match exactly
        run: cmp -s first/${{ inputs.target }}.pdf second/${{ inputs.target }}.pdf


  build_ebook:
    name: Build ebook ${{ inputs.target }}
    if: inputs.publish == true

    uses: ./.github/workflows/build_ebook.yml
    with:
      texlive_digest: ${{ inputs.texlive_digest }}
      timestamp: ${{ inputs.timestamp }}
      filename: ${{ inputs.target }}
      pre_tex: '\def\NOTAG{} ${{ inputs.pre_tex }}'
      publish: ${{ inputs.publish }}
